config/routes.rb
Rails.application.routes.draw do
  resources :gym_enquetes
  resources :food_enquetes
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/food_enquete.rb
class FoodEnquete < ApplicationRecord
  include CommonModule  # 「お食事」と「スポーツジム」モデルの共通モジュール

  ADULIT_AGE = 20

  # 食事した料理 必須入力 数値 整数のみ 0〜2 (0:ラーメン 1:カレー 2:やきそば)
  validates :food_id, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 0, less_than_or_equal_to: 2 }

  # 応募するプレゼント 必須入力 数値 整数のみ 0〜1 (0:ソフトドリンク飲み放題 1:ビール飲み放題)
  validates :present_id, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 0, less_than_or_equal_to: 1 }

  # 未成年が選択できないプレゼントか検証
  validate :cannot_present_to_minor

  # 食事した料理の選択肢 ラーメン、カレー、やきそば
  @@foods  = [
    { id: 0, 
      name: FoodEnquete.human_attribute_name(:food_list)[0][:name], 
      price: FoodEnquete.human_attribute_name(:food_list)[0][:price] }, 
    { id: 1, 
      name: FoodEnquete.human_attribute_name(:food_list)[1][:name], 
      price: FoodEnquete.human_attribute_name(:food_list)[1][:price] }, 
    { id: 2, 
      name: FoodEnquete.human_attribute_name(:food_list)[2][:name], 
      price: FoodEnquete.human_attribute_name(:food_list)[2][:price] }
  ]

  # プレゼントの選択肢 ソフトドリンク飲み放題、ビール飲み放題
  @@presents  = [
    { id: 0, 
      name: FoodEnquete.human_attribute_name(:present_list)[0][:name], 
      price: FoodEnquete.human_attribute_name(:present_list)[0][:price], 
      adult_only: false }, 
    { id: 1, 
      name: FoodEnquete.human_attribute_name(:present_list)[1][:name], 
      price: FoodEnquete.human_attribute_name(:present_list)[1][:price], 
      adult_only: true }
  ]

  #
  # 食事した料理のリストを作成します。
  # 料理の名前、価格、消費税込みの価格がアンケートフォームに表示されます。
  #
  # @return [String] アンケートフォームに表示する料理のリスト
  #
  def food_choices
    @@foods.map {|item| [I18n.t('common.price_and_tax', name: item[:name], price: item[:price], tax_included_price: tax_included_price(item[:price])), item[:id]] }
  end

  #
  # プレゼントのリストを作成します。
  # プレゼントの名前、価格、消費税込みの価格がアンケートフォームに表示されます。
  #
  # @return [String] アンケートフォームに表示するプレゼントのリスト
  #
  def present_choices
    @@presents.map {|item| [I18n.t('common.price_and_tax', name: item[:name], price: item[:price], tax_included_price: tax_included_price(item[:price])), item[:id]] }
  end

  #
  # 選択された料理の名前を表示します。
  #
  # @return [String] 一覧や詳細ページに表示する料理の名前
  #
  def food_name
    food = @@foods.find { |food| food[:id] == food_id }
    food&.dig :name
  end

  #
  # 選択されたプレゼントの名前を表示します。
  #
  # @return [String] 一覧や詳細ページに表示するプレゼントの名前
  #
  def present_name
    present = @@presents.find { |present| present[:id] == present_id }
    present&.dig :name
  end

  private
  #
  # 未成年が選択できないプレゼントか検証するバリデーションです。
  #
  def cannot_present_to_minor
    return if age.nil?
    if !adult?(age) && @@presents.any? { |present| present[:id] == present_id && present[:adult_only] == true }
      errors.add(:present_id, :cannot_present_to_minor)
    end
  end

  #
  # 未成年が選択できないプレゼントか検証するバリデーションです。
  # @param age [Integer] 年齢
  # @return [True] 成人
  # @return [False] 未成年
  #
  def adult?(age)
    age >= ADULIT_AGE
  end
end

app/controllers/food_enquetes_controller.rb
class FoodEnquetesController < ApplicationController
  before_action :set_food_enquete, only: [:show, :edit, :update, :destroy]

  # GET /food_enquetes
  def index
    @food_enquetes = FoodEnquete.all
  end

  # GET /food_enquetes/1
  def show
  end

  # GET /food_enquetes/new
  def new
    @food_enquete = FoodEnquete.new
  end

  # GET /food_enquetes/1/edit
  def edit
  end

  # POST /food_enquetes
  def create
    @food_enquete = FoodEnquete.new(food_enquete_params)

    if @food_enquete.save
      redirect_to @food_enquete, notice: I18n.t('successes.submit', name: @food_enquete.model_name.human)
    else
      render :new
    end
  end

  # PATCH/PUT /food_enquetes/1
  def update
    if @food_enquete.update(food_enquete_params)
      redirect_to @food_enquete, notice: I18n.t('successes.update', name: @food_enquete.model_name.human)
    else
      render :edit
    end
  end

  # DELETE /food_enquetes/1
  def destroy
    @food_enquete.destroy
    redirect_to food_enquetes_url, notice: I18n.t('successes.destroy', name: @food_enquete.model_name.human)
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_food_enquete
    @food_enquete = FoodEnquete.find(params[:id])
  end

  # Only allow a trusted parameter "white list" through.
  def food_enquete_params
    params.require(:food_enquete).permit(:name, :mail, :age, :food_id, :score, :request, :present_id)
  end
end

app/helpers/food_enquetes_helper.rb
module FoodEnquetesHelper
end

app/views/food_enquetes/_form.html.erb
<%= form_with(model: food_enquete, local: true) do |form| %>
  <% if food_enquete.errors.any? %>
    <div id="error_explanation">
      <ul>
        <% food_enquete.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= render 'concerns/form_name_mail_age', form: form %>

  <div class="field">
    <%= form.label :food_id %>
    <%= form.select :food_id, food_enquete.food_choices %><%# ラーメン、カレー、やきそば %>
  </div>

  <%= render 'concerns/form_score_request', form: form %>

  <div class="field">
    <%= form.label :present_id %>
    <%= form.select :present_id, food_enquete.present_choices %><%# ソフトドリンク飲み放題、ビール飲み放題 %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/food_enquetes/edit.html.erb
<h1><%= t 'food_enquetes.common.title' %></h1>

<%= render 'form', food_enquete: @food_enquete %>

<%= link_to (t 'common.show'), @food_enquete %> |
<%= link_to (t 'common.back'), food_enquetes_path %>

app/views/food_enquetes/index.html.erb
<p id="notice"><%= notice %></p>

<h1><%= t 'food_enquetes.index.title' %></h1>

<table>
  <thead>
  <tr>
    <th><%= FoodEnquete.human_attribute_name(:name) %></th>
    <th><%= FoodEnquete.human_attribute_name(:mail) %></th>
    <th><%= FoodEnquete.human_attribute_name(:age) %></th>
    <th><%= FoodEnquete.human_attribute_name(:food_id) %></th>
    <th><%= FoodEnquete.human_attribute_name(:score) %></th>
    <th><%= FoodEnquete.human_attribute_name(:request) %></th>
    <th><%= FoodEnquete.human_attribute_name(:present_id) %></th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
  <% @food_enquetes.each do |food_enquete| %>
    <tr>
      <td><%= food_enquete.name %></td>
      <td><%= food_enquete.mail %></td>
      <td><%= food_enquete.age %></td>
      <td><%= food_enquete.food_name %></td>
      <td><%= food_enquete.view_score %></td>
      <td><%= food_enquete.request %></td>
      <td><%= food_enquete.present_name %></td>
      <td><%= link_to (t 'common.show'), food_enquete %></td>
      <td><%= link_to (t 'common.edit'), edit_food_enquete_path(food_enquete) %></td>
      <td><%= link_to (t 'common.index.destroy'), food_enquete, method: :delete, data: { confirm: (t 'common.index.destroy_confirm') } %></td>
    </tr>
  <% end %>
  </tbody>
</table>

<br>

<%= link_to (t 'common.new'), new_food_enquete_path %>

app/views/food_enquetes/new.html.erb
<h1><%= t 'food_enquetes.common.title' %></h1>

<%= render 'form', food_enquete: @food_enquete %>

<%= link_to (t 'common.back'), food_enquetes_path %>

app/views/food_enquetes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong><%= FoodEnquete.human_attribute_name(:name) %>:</strong>
  <%= @food_enquete.name %>
</p>

<p>
  <strong><%= FoodEnquete.human_attribute_name(:mail) %>:</strong>
  <%= @food_enquete.mail %>
</p>

<p>
  <strong><%= FoodEnquete.human_attribute_name(:age) %>:</strong>
  <%= @food_enquete.age %>
</p>

<p>
  <strong><%= FoodEnquete.human_attribute_name(:food_id) %>:</strong>
  <%= @food_enquete.food_name %>
</p>

<p>
  <strong><%= FoodEnquete.human_attribute_name(:score) %>:</strong>
  <%= @food_enquete.view_score %>
</p>

<p>
  <strong><%= FoodEnquete.human_attribute_name(:request) %>:</strong>
  <%= @food_enquete.request %>
</p>

<p>
  <strong><%= FoodEnquete.human_attribute_name(:present_id) %>:</strong>
  <%= @food_enquete.present_name %>
</p>

<%= link_to (t 'common.edit'), edit_food_enquete_path(@food_enquete) %> |
<%= link_to (t 'common.back'), food_enquetes_path %>