config/routes.rb
Rails.application.routes.draw do
  resources :gym_enquetes
  resources :food_enquetes
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/gym_enquete.rb
class GymEnquete < ApplicationRecord
  include CommonModule # 「お食事」と「スポーツジム」モデルの共通モジュール

  # 参加したコース 必須入力 数値 整数のみ 0〜1 (0:脂肪燃焼 1:ヨガ)
  validates :course_id, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 0, less_than_or_equal_to: 1 }

  # 応募するプレゼント 必須入力 数値 整数のみ 0〜1 (0:サプリメントセット 1:温泉旅行)
  validates :present_id, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 0, less_than_or_equal_to: 1 }

  # 参加したコースの選択肢 脂肪燃焼、ヨガ
  @@courses  = [
      { id: 0,
        name: GymEnquete.human_attribute_name(:course_list)[0][:name],
        price: GymEnquete.human_attribute_name(:course_list)[0][:price] },
      { id: 1,
        name: GymEnquete.human_attribute_name(:course_list)[1][:name],
        price: GymEnquete.human_attribute_name(:course_list)[1][:price] }
  ]

  # プレゼントの選択肢 サプリメントセット、温泉旅行
  @@presents  = [
      { id: 0, name: GymEnquete.human_attribute_name(:present_list)[0][:name] },
      { id: 1, name: GymEnquete.human_attribute_name(:present_list)[1][:name] }
  ]

  #
  # 参加したコースのリストを作成します。
  # コースの名前、価格、消費税込みの価格がアンケートフォームに表示されます。
  #
  # @return [String] アンケートフォームに表示するコースのリスト
  #
  def course_choices
    @@courses.map {|item| [I18n.t('common.price_and_tax', name: item[:name], price: item[:price], tax_included_price: tax_included_price(item[:price])), item[:id]] }
  end

  #
  # プレゼントのリストを作成します。
  # プレゼントの名前、価格、消費税込みの価格がアンケートフォームに表示されます。
  #
  # @return [String] アンケートフォームに表示するプレゼントのリスト
  #
  def present_choices
    @@presents.map {|item| [item[:name], item[:id]] }
  end

  #
  # 選択されたコースの名前を表示します。
  #
  # @return [String] 一覧や詳細ページに表示するコースの名前
  #
  def course_name
    course = @@courses.find { |course| course[:id] == course_id }
    course&.dig :name
  end

  #
  # 選択されたプレゼントの名前を表示します。
  #
  # @return [String] 一覧や詳細ページに表示するプレゼントの名前
  #
  def present_name
    present = @@presents.find { |present| present[:id] == present_id }
    present&.dig :name
  end
end

app/controllers/gym_enquetes_controller.rb
class GymEnquetesController < ApplicationController
  before_action :set_gym_enquete, only: [:show, :edit, :update, :destroy]

  # GET /gym_enquetes
  def index
    @gym_enquetes = GymEnquete.all
  end

  # GET /gym_enquetes/1
  def show
  end

  # GET /gym_enquetes/new
  def new
    @gym_enquete = GymEnquete.new
  end

  # GET /gym_enquetes/1/edit
  def edit
  end

  # POST /gym_enquetes
  def create
    @gym_enquete = GymEnquete.new(gym_enquete_params)

    if @gym_enquete.save
      redirect_to @gym_enquete, notice: I18n.t('successes.submit', name: @gym_enquete.model_name.human)
    else
      render :new
    end
  end

  # PATCH/PUT /gym_enquetes/1
  def update
    if @gym_enquete.update(gym_enquete_params)
      redirect_to @gym_enquete, notice: I18n.t('successes.update', name: @gym_enquete.model_name.human)
    else
      render :edit
    end
  end

  # DELETE /gym_enquetes/1
  def destroy
    @gym_enquete.destroy
    redirect_to gym_enquetes_url, notice: I18n.t('successes.destroy', name: @gym_enquete.model_name.human)
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_gym_enquete
    @gym_enquete = GymEnquete.find(params[:id])
  end

  # Only allow a trusted parameter "white list" through.
  def gym_enquete_params
    params.require(:gym_enquete).permit(:name, :mail, :age, :course_id, :score, :request, :present_id)
  end
end

app/helpers/gym_enquetes_helper.rb
module GymEnquetesHelper
end

app/views/gym_enquetes/_form.html.erb
<%= form_with(model: gym_enquete, local: true) do |form| %>
  <% if gym_enquete.errors.any? %>
    <div id="error_explanation">
      <ul>
        <% gym_enquete.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= render 'concerns/form_name_mail_age', form: form %>

  <div class="field">
    <%= form.label :course_id %>
    <%= form.select :course_id, gym_enquete.course_choices %><%# 脂肪燃焼、ヨガ %>
  </div>

  <%= render 'concerns/form_score_request', form: form %>

  <div class="field">
    <%= form.label :present_id %>
    <%= form.select :present_id, gym_enquete.present_choices %><%# サプリメントセット、温泉旅行 %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/gym_enquetes/edit.html.erb
<h1><%= t 'gym_enquetes.common.title' %></h1>

<%= render 'form', gym_enquete: @gym_enquete %>

<%= link_to (t 'common.show'), @gym_enquete %> |
<%= link_to (t 'common.back'), gym_enquetes_path %>

app/views/gym_enquetes/index.html.erb
<p id="notice"><%= notice %></p>

<h1><%= t 'gym_enquetes.index.title' %></h1>

<table>
  <thead>
  <tr>
    <th><%= GymEnquete.human_attribute_name(:name) %></th>
    <th><%= GymEnquete.human_attribute_name(:mail) %></th>
    <th><%= GymEnquete.human_attribute_name(:age) %></th>
    <th><%= GymEnquete.human_attribute_name(:course_id) %></th>
    <th><%= GymEnquete.human_attribute_name(:score) %></th>
    <th><%= GymEnquete.human_attribute_name(:request) %></th>
    <th><%= GymEnquete.human_attribute_name(:present_id) %></th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
  <% @gym_enquetes.each do |gym_enquete| %>
    <tr>
      <td><%= gym_enquete.name %></td>
      <td><%= gym_enquete.mail %></td>
      <td><%= gym_enquete.age %></td>
      <td><%= gym_enquete.course_name %></td>
      <td><%= gym_enquete.view_score %></td>
      <td><%= gym_enquete.request %></td>
      <td><%= gym_enquete.present_name %></td>
      <td><%= link_to (t 'common.show'), gym_enquete %></td>
      <td><%= link_to (t 'common.edit'), edit_gym_enquete_path(gym_enquete) %></td>
      <td><%= link_to (t 'common.index.destroy'), gym_enquete, method: :delete, data: { confirm: (t 'common.index.destroy_confirm') } %></td>
    </tr>
  <% end %>
  </tbody>
</table>

<br>

<%= link_to (t 'common.new'), new_gym_enquete_path %>

app/views/gym_enquetes/new.html.erb
<h1><%= t 'gym_enquetes.common.title' %></h1>

<%= render 'form', gym_enquete: @gym_enquete %>

<%= link_to (t 'common.back'), gym_enquetes_path %>

app/views/gym_enquetes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong><%= GymEnquete.human_attribute_name(:name) %>:</strong>
  <%= @gym_enquete.name %>
</p>

<p>
  <strong><%= GymEnquete.human_attribute_name(:mail) %>:</strong>
  <%= @gym_enquete.mail %>
</p>

<p>
  <strong><%= GymEnquete.human_attribute_name(:age) %>:</strong>
  <%= @gym_enquete.age %>
</p>

<p>
  <strong><%= GymEnquete.human_attribute_name(:course_id) %>:</strong>
  <%= @gym_enquete.course_name %>
</p>

<p>
  <strong><%= GymEnquete.human_attribute_name(:score) %>:</strong>
  <%= @gym_enquete.view_score %>
</p>

<p>
  <strong><%= GymEnquete.human_attribute_name(:request) %>:</strong>
  <%= @gym_enquete.request %>
</p>

<p>
  <strong><%= GymEnquete.human_attribute_name(:present_id) %>:</strong>
  <%= @gym_enquete.present_name %>
</p>

<%= link_to (t 'common.edit'), edit_gym_enquete_path(@gym_enquete) %> |
<%= link_to (t 'common.back'), gym_enquetes_path %>